---
- name: Configure Fask and Server
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install dependencies
    yum:
      name: [ "python3-pip", "nginx" ]
      state: present
    become: true

  - name: Install Flask
    pip:
      name: flask

  - name: Start app
    shell: nohup python3 /tmp/cloudops-pipeline-end-to-end-devops-on-aws/app/app.py &
